CREATE TABLE IF NOT EXISTS `DTSTRMOV` (
	`GSDATE` VARCHAR(8) NOT NULL COMMENT '자료일자',
	`GSTIME` VARCHAR(4) NOT NULL COMMENT '자료시각',
	`STCODE` VARCHAR(10) NOT NULL COMMENT '종목코드',
	`TD_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인당일',
	`TD_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관당일',
	`YD_RATE` DECIMAL(7,3) NULL DEFAULT NULL COMMENT '전일대비율',
	`YD_TR_RATE` DECIMAL(11,3) NULL DEFAULT NULL COMMENT '전일거래량 대비율',
	`STOT_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인잠정',
	`STOT_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관잠정',
	`YD_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인전일',
	`YD_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관전일',
	`RATE_RESERVE` DECIMAL(9,3) NULL DEFAULT NULL COMMENT '유보율(분기)',
	`EV_EBITDA` DECIMAL(7,3) NULL DEFAULT NULL COMMENT 'EV/EBITDA(기업가치/영업력 배수)',
	PRIMARY KEY (`GSDATE`, `GSTIME`, `STCODE`)
)
COMMENT='강력출동'
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

CREATE TABLE IF NOT EXISTS `DTTR20` (
	`GSDATE` VARCHAR(8) NOT NULL COMMENT '자료일자',
	`GSTIME` VARCHAR(4) NOT NULL COMMENT '자료시각',
	`STCODE` VARCHAR(10) NOT NULL COMMENT '종목코드',
	`TD_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인당일',
	`TD_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관당일',
	`YD_RATE` DECIMAL(7,3) NULL DEFAULT NULL COMMENT '전일대비율',
	`YD_TR_RATE` DECIMAL(11,3) NULL DEFAULT NULL COMMENT '전일거래량 대비율',
	`STOT_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인잠정',
	`STOT_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관잠정',
	`YD_FOREIGN` INT(11) NULL DEFAULT NULL COMMENT '외인전일',
	`YD_INVEST` INT(11) NULL DEFAULT NULL COMMENT '기관전일',
	`RATE_RESERVE` DECIMAL(9,3) NULL DEFAULT NULL COMMENT '유보율(분기)',
	`EV_EBITDA` DECIMAL(7,3) NULL DEFAULT NULL COMMENT 'EV/EBITDA(기업가치/영업력 배수)',
	PRIMARY KEY (`GSDATE`, `GSTIME`, `STCODE`)
)
COMMENT='거래20이평'
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;


ALTER TABLE `DTFGNINVTR`
	CHANGE COLUMN `YD_TR_RATE` `YD_TR_RATE` DECIMAL(11,3) NULL DEFAULT NULL COMMENT '전일거래량 대비율' AFTER `YD_RATE`;

ALTER TABLE `DTFGNTR`
	CHANGE COLUMN `YD_TR_RATE` `YD_TR_RATE` DECIMAL(11,3) NULL DEFAULT NULL COMMENT '전일거래량 대비율' AFTER `YD_RATE`;

ALTER TABLE `DTINVTR`
	CHANGE COLUMN `YD_TR_RATE` `YD_TR_RATE` DECIMAL(11,3) NULL DEFAULT NULL COMMENT '전일거래량 대비율' AFTER `YD_RATE`;

